/**
 * Liste de référence marques / modèles (marché MA / import courant).
 * Chaque entrée : nom FR, nom AR indicatif, segment prix (tier), type carrosserie.
 */
export type RefBody = "CITY_CAR" | "SEDAN" | "SUV" | "COMMERCIAL" | "PICKUP" | "FAMILY";

export type RefModelRow = { modelFr: string; modelAr: string; body: RefBody };

export type RefBrandRow = { brandFr: string; brandAr: string; tier: number; models: RefModelRow[] };

const m = (modelFr: string, modelAr: string, body: RefBody): RefModelRow => ({ modelFr, modelAr, body });

export const REFERENCE_BRANDS: RefBrandRow[] = [
  {
    brandFr: "Dacia",
    brandAr: "داسيا",
    tier: 0,
    models: [
      m("Logan", "لوغان", "SEDAN"),
      m("Sandero", "سانديرو", "CITY_CAR"),
      m("Sandero Stepway", "سانديرو ستيبوي", "SUV"),
      m("Duster", "دوستر", "SUV"),
      m("Jogger", "جوغر", "FAMILY"),
      m("Lodgy", "لودجي", "FAMILY"),
      m("Dokker", "دوكر", "COMMERCIAL"),
      m("Spring", "سبرينغ", "CITY_CAR"),
      m("Bigster", "بيغستر", "SUV"),
    ],
  },
  {
    brandFr: "Renault",
    brandAr: "رينو",
    tier: 0,
    models: [
      m("Clio", "كليو", "CITY_CAR"),
      m("Megane", "ميغان", "FAMILY"),
      m("Taliant", "تاليانت", "SEDAN"),
      m("Captur", "كابتشر", "SUV"),
      m("Austral", "أوسترال", "SUV"),
      m("Arkana", "أركانا", "SUV"),
      m("Koleos", "كوليوس", "SUV"),
      m("Express", "إكسبريس", "COMMERCIAL"),
      m("Kangoo", "كانغو", "COMMERCIAL"),
      m("Kardian", "كارديان", "SUV"),
      m("Zoe", "زوي", "CITY_CAR"),
      m("Scenic", "سينيك", "FAMILY"),
      m("Laguna", "لاغونا", "SEDAN"),
    ],
  },
  {
    brandFr: "Peugeot",
    brandAr: "بيجو",
    tier: 1,
    models: [
      m("108", "108", "CITY_CAR"),
      m("208", "208", "CITY_CAR"),
      m("301", "301", "SEDAN"),
      m("308", "308", "FAMILY"),
      m("408", "408", "SEDAN"),
      m("508", "508", "SEDAN"),
      m("2008", "2008", "SUV"),
      m("3008", "3008", "SUV"),
      m("5008", "5008", "SUV"),
      m("Partner", "بارتنر", "COMMERCIAL"),
      m("Rifter", "ريفتر", "COMMERCIAL"),
      m("Boxer", "بوكسر", "COMMERCIAL"),
    ],
  },
  {
    brandFr: "Citroen",
    brandAr: "ستروين",
    tier: 1,
    models: [
      m("C1", "C1", "CITY_CAR"),
      m("C3", "C3", "CITY_CAR"),
      m("C3 Aircross", "C3 إيركروس", "SUV"),
      m("C4", "C4", "FAMILY"),
      m("C4X", "C4 إكس", "SUV"),
      m("C5 Aircross", "C5 إيركروس", "SUV"),
      m("Berlingo", "برلينغو", "COMMERCIAL"),
      m("Jumper", "جمبر", "COMMERCIAL"),
    ],
  },
  {
    brandFr: "DS",
    brandAr: "دي إس",
    tier: 2,
    models: [
      m("DS 3", "دي إس 3", "CITY_CAR"),
      m("DS 4", "دي إس 4", "FAMILY"),
      m("DS 7", "دي إس 7", "SUV"),
      m("DS 9", "دي إس 9", "SEDAN"),
    ],
  },
  {
    brandFr: "Volkswagen",
    brandAr: "فولكسفاغن",
    tier: 1,
    models: [
      m("Polo", "بولو", "CITY_CAR"),
      m("Golf", "غولف", "FAMILY"),
      m("Passat", "باسات", "SEDAN"),
      m("Arteon", "أرتيون", "SEDAN"),
      m("Jetta", "جيتا", "SEDAN"),
      m("T-Cross", "تي كروس", "SUV"),
      m("T-Roc", "تي روك", "SUV"),
      m("Tiguan", "تيجوان", "SUV"),
      m("Touareg", "طوارق", "SUV"),
      m("Amarok", "أماروك", "PICKUP"),
      m("ID.4", "آي دي 4", "SUV"),
    ],
  },
  {
    brandFr: "Audi",
    brandAr: "أودي",
    tier: 3,
    models: [
      m("A1", "A1", "CITY_CAR"),
      m("A3", "A3", "FAMILY"),
      m("A4", "A4", "SEDAN"),
      m("A5", "A5", "FAMILY"),
      m("A6", "A6", "SEDAN"),
      m("A7", "A7", "SEDAN"),
      m("A8", "A8", "SEDAN"),
      m("Q2", "Q2", "SUV"),
      m("Q3", "Q3", "SUV"),
      m("Q5", "Q5", "SUV"),
      m("Q7", "Q7", "SUV"),
      m("Q8", "Q8", "SUV"),
      m("e-tron", "إي ترون", "SUV"),
    ],
  },
  {
    brandFr: "BMW",
    brandAr: "بي إم دبليو",
    tier: 3,
    models: [
      m("Série 1", "الفئة 1", "CITY_CAR"),
      m("Série 2", "الفئة 2", "FAMILY"),
      m("Série 3", "الفئة 3", "SEDAN"),
      m("Série 4", "الفئة 4", "FAMILY"),
      m("Série 5", "الفئة 5", "SEDAN"),
      m("Série 7", "الفئة 7", "SEDAN"),
      m("Série 8", "الفئة 8", "FAMILY"),
      m("X1", "X1", "SUV"),
      m("X2", "X2", "SUV"),
      m("X3", "X3", "SUV"),
      m("X4", "X4", "SUV"),
      m("X5", "X5", "SUV"),
      m("X6", "X6", "SUV"),
      m("X7", "X7", "SUV"),
      m("i4", "i4", "SEDAN"),
      m("i5", "i5", "SEDAN"),
      m("i7", "i7", "SEDAN"),
      m("iX", "iX", "SUV"),
      m("Z4", "Z4", "FAMILY"),
    ],
  },
  {
    brandFr: "Mercedes",
    brandAr: "مرسيدس",
    tier: 3,
    models: [
      m("Classe A", "الفئة A", "CITY_CAR"),
      m("Classe B", "الفئة B", "FAMILY"),
      m("Classe C", "الفئة C", "SEDAN"),
      m("Classe E", "الفئة E", "SEDAN"),
      m("Classe S", "الفئة S", "SEDAN"),
      m("CLA", "CLA", "FAMILY"),
      m("CLS", "CLS", "SEDAN"),
      m("GLA", "GLA", "SUV"),
      m("GLB", "GLB", "SUV"),
      m("GLC", "GLC", "SUV"),
      m("GLE", "GLE", "SUV"),
      m("GLS", "GLS", "SUV"),
      m("Classe G", "الفئة G", "SUV"),
      m("EQA", "EQA", "SUV"),
      m("EQB", "EQB", "SUV"),
      m("EQE", "EQE", "SEDAN"),
      m("EQS", "EQS", "SEDAN"),
      m("Vito", "فيتو", "COMMERCIAL"),
      m("Sprinter", "سبرينتر", "COMMERCIAL"),
    ],
  },
  {
    brandFr: "Opel",
    brandAr: "أوبل",
    tier: 1,
    models: [
      m("Corsa", "كورسا", "CITY_CAR"),
      m("Astra", "أسترا", "FAMILY"),
      m("Crossland", "كروسلاند", "SUV"),
      m("Grandland", "غراندلاند", "SUV"),
      m("Mokka", "موكا", "SUV"),
      m("Combo", "كومبو", "COMMERCIAL"),
    ],
  },
  {
    brandFr: "Toyota",
    brandAr: "تويوتا",
    tier: 1,
    models: [
      m("Yaris", "ياريس", "CITY_CAR"),
      m("Corolla", "كورولا", "SEDAN"),
      m("Camry", "كامري", "SEDAN"),
      m("Prius", "بريوس", "FAMILY"),
      m("Hilux", "هايلكس", "PICKUP"),
      m("RAV4", "راف 4", "SUV"),
      m("Land Cruiser", "لاند كروزر", "SUV"),
      m("Prado", "برادو", "SUV"),
      m("Fortuner", "فورتشنر", "SUV"),
      m("Aygo", "آيغو", "CITY_CAR"),
      m("C-HR", "سي إتش آر", "SUV"),
    ],
  },
  {
    brandFr: "Honda",
    brandAr: "هوندا",
    tier: 1,
    models: [
      m("Civic", "سيفيك", "FAMILY"),
      m("Accord", "أكورد", "SEDAN"),
      m("City", "سيتي", "SEDAN"),
      m("Jazz", "جاز", "CITY_CAR"),
      m("HR-V", "إتش آر في", "SUV"),
      m("CR-V", "سي آر في", "SUV"),
      m("Pilot", "بايلوت", "SUV"),
    ],
  },
  {
    brandFr: "Nissan",
    brandAr: "نيسان",
    tier: 1,
    models: [
      m("Micra", "ميكرا", "CITY_CAR"),
      m("Sunny", "صني", "SEDAN"),
      m("Sentra", "سنترا", "SEDAN"),
      m("Juke", "جوك", "SUV"),
      m("Qashqai", "قاشقاي", "SUV"),
      m("X-Trail", "إكس تريل", "SUV"),
      m("Patrol", "باترول", "SUV"),
      m("Navara", "نافارا", "PICKUP"),
    ],
  },
  {
    brandFr: "Mazda",
    brandAr: "مازدا",
    tier: 1,
    models: [
      m("Mazda 2", "مازدا 2", "CITY_CAR"),
      m("Mazda 3", "مازدا 3", "FAMILY"),
      m("Mazda 6", "مازدا 6", "SEDAN"),
      m("CX-3", "CX-3", "SUV"),
      m("CX-5", "CX-5", "SUV"),
      m("CX-60", "CX-60", "SUV"),
      m("MX-5", "MX-5", "FAMILY"),
    ],
  },
  {
    brandFr: "Suzuki",
    brandAr: "سوزوكي",
    tier: 0,
    models: [
      m("Alto", "ألتو", "CITY_CAR"),
      m("Celerio", "سيليريو", "CITY_CAR"),
      m("Swift", "سويفت", "CITY_CAR"),
      m("Baleno", "بالينو", "FAMILY"),
      m("Dzire", "دزاير", "SEDAN"),
      m("Vitara", "فيتارا", "SUV"),
      m("Jimny", "جمني", "SUV"),
      m("S-Cross", "إس كروس", "SUV"),
    ],
  },
  {
    brandFr: "Mitsubishi",
    brandAr: "ميتسوبيشي",
    tier: 1,
    models: [
      m("Mirage", "ميراج", "CITY_CAR"),
      m("L200", "L200", "PICKUP"),
      m("Pajero", "باجيرو", "SUV"),
      m("Outlander", "أوتلاندر", "SUV"),
      m("Eclipse Cross", "إكليبس كروس", "SUV"),
    ],
  },
  {
    brandFr: "Hyundai",
    brandAr: "هيونداي",
    tier: 1,
    models: [
      m("i10", "i10", "CITY_CAR"),
      m("i20", "i20", "CITY_CAR"),
      m("Accent", "أكسنت", "SEDAN"),
      m("Elantra", "إلنترا", "SEDAN"),
      m("Sonata", "سوناتا", "SEDAN"),
      m("Tucson", "توسان", "SUV"),
      m("Santa Fe", "سانتا في", "SUV"),
      m("Creta", "كريتا", "SUV"),
      m("Kona", "كونا", "SUV"),
      m("Venue", "فينيو", "SUV"),
      m("Staria", "ستاريا", "COMMERCIAL"),
    ],
  },
  {
    brandFr: "Kia",
    brandAr: "كيا",
    tier: 1,
    models: [
      m("Picanto", "بيكانتو", "CITY_CAR"),
      m("Rio", "ريو", "CITY_CAR"),
      m("Cerato", "سيراتو", "SEDAN"),
      m("K5", "K5", "SEDAN"),
      m("Seltos", "سيلتوس", "SUV"),
      m("Sportage", "سبورتاج", "SUV"),
      m("Sorento", "سورينتو", "SUV"),
      m("Carnival", "كارنفال", "FAMILY"),
      m("EV5", "EV5", "SUV"),
      m("EV6", "EV6", "SUV"),
    ],
  },
  {
    brandFr: "Ford",
    brandAr: "فورد",
    tier: 1,
    models: [
      m("Fiesta", "فييستا", "CITY_CAR"),
      m("Focus", "فوكس", "FAMILY"),
      m("Mondeo", "مونديو", "SEDAN"),
      m("Mustang", "موستانغ", "FAMILY"),
      m("Puma", "بوما", "SUV"),
      m("Kuga", "كوغا", "SUV"),
      m("Everest", "إيفرست", "SUV"),
      m("Ranger", "رينجر", "PICKUP"),
      m("Explorer", "إكسبلورر", "SUV"),
    ],
  },
  {
    brandFr: "Chevrolet",
    brandAr: "شيفروليه",
    tier: 1,
    models: [
      m("Spark", "سبارك", "CITY_CAR"),
      m("Aveo", "أفيو", "CITY_CAR"),
      m("Malibu", "ماليبو", "SEDAN"),
      m("Captiva", "كابتيفا", "SUV"),
      m("Tahoe", "تاهو", "SUV"),
    ],
  },
  {
    brandFr: "Jeep",
    brandAr: "جيب",
    tier: 2,
    models: [
      m("Renegade", "رينيغيد", "SUV"),
      m("Compass", "كومباس", "SUV"),
      m("Cherokee", "شيروكي", "SUV"),
      m("Wrangler", "رانغلر", "SUV"),
      m("Grand Cherokee", "غراند شيروكي", "SUV"),
    ],
  },
  {
    brandFr: "Fiat",
    brandAr: "فيات",
    tier: 1,
    models: [
      m("Panda", "باندا", "CITY_CAR"),
      m("Tipo", "تيبو", "FAMILY"),
      m("500", "500", "CITY_CAR"),
      m("500X", "500X", "SUV"),
      m("Doblo", "دوبلو", "COMMERCIAL"),
      m("Fiorino", "فيورينو", "COMMERCIAL"),
      m("Ducato", "دوكاتو", "COMMERCIAL"),
    ],
  },
  {
    brandFr: "Alfa Romeo",
    brandAr: "ألفا روميو",
    tier: 3,
    models: [
      m("Giulietta", "جولييتا", "FAMILY"),
      m("Giulia", "جوليا", "SEDAN"),
      m("Stelvio", "ستلفيو", "SUV"),
      m("Tonale", "تونالي", "SUV"),
      m("Junior", "جونيور", "SUV"),
    ],
  },
  {
    brandFr: "Land Rover",
    brandAr: "لاند روفر",
    tier: 3,
    models: [
      m("Defender", "ديفندر", "SUV"),
      m("Discovery", "ديسكفري", "SUV"),
      m("Discovery Sport", "ديسكفري سبورت", "SUV"),
      m("Range Rover", "رينج روفر", "SUV"),
      m("Range Rover Sport", "رينج روفر سبورت", "SUV"),
      m("Evoque", "إيفوك", "SUV"),
      m("Velar", "فيلار", "SUV"),
    ],
  },
  {
    brandFr: "Volvo",
    brandAr: "فولفو",
    tier: 2,
    models: [
      m("S60", "S60", "SEDAN"),
      m("S90", "S90", "SEDAN"),
      m("XC40", "XC40", "SUV"),
      m("XC60", "XC60", "SUV"),
      m("XC90", "XC90", "SUV"),
      m("EX30", "EX30", "SUV"),
    ],
  },
  {
    brandFr: "Lexus",
    brandAr: "لكزس",
    tier: 3,
    models: [
      m("IS", "IS", "SEDAN"),
      m("ES", "ES", "SEDAN"),
      m("LS", "LS", "SEDAN"),
      m("NX", "NX", "SUV"),
      m("RX", "RX", "SUV"),
      m("LX", "LX", "SUV"),
    ],
  },
  {
    brandFr: "BYD",
    brandAr: "بي واي دي",
    tier: 1,
    models: [
      m("Dolphin", "دولفين", "CITY_CAR"),
      m("Seal", "سيل", "SEDAN"),
      m("Seal U", "سيل يو", "SUV"),
      m("Atto 3", "أتو 3", "SUV"),
      m("Han", "هان", "SEDAN"),
      m("Tang", "تانغ", "SUV"),
    ],
  },
  {
    brandFr: "Chery",
    brandAr: "شيري",
    tier: 1,
    models: [
      m("Tiggo 2", "تيجو 2", "SUV"),
      m("Tiggo 3X", "تيجو 3X", "SUV"),
      m("Tiggo 4 Pro", "تيجو 4 برو", "SUV"),
      m("Tiggo 7 Pro", "تيجو 7 برو", "SUV"),
      m("Tiggo 8 Pro", "تيجو 8 برو", "SUV"),
      m("EQ1", "EQ1", "CITY_CAR"),
    ],
  },
  {
    brandFr: "MG",
    brandAr: "إم جي",
    tier: 1,
    models: [
      m("MG3", "MG3", "CITY_CAR"),
      m("MG4", "MG4", "FAMILY"),
      m("ZS", "ZS", "SUV"),
      m("HS", "HS", "SUV"),
      m("RX5", "RX5", "SUV"),
    ],
  },
  {
    brandFr: "Haval",
    brandAr: "هافال",
    tier: 1,
    models: [m("Jolion", "جوليون", "SUV"), m("H6", "H6", "SUV"), m("Dargo", "دارغو", "SUV")],
  },
  {
    brandFr: "Geely",
    brandAr: "جيلي",
    tier: 1,
    models: [m("GX3 Pro", "GX3 برو", "SUV"), m("Coolray", "كولراي", "SUV"), m("Tugella", "توجيلا", "SUV")],
  },
  {
    brandFr: "GWM",
    brandAr: "جي دبليو إم",
    tier: 1,
    models: [m("Poer", "بوير", "PICKUP"), m("Tank 300", "تانك 300", "SUV")],
  },
  {
    brandFr: "Skoda",
    brandAr: "سكودا",
    tier: 1,
    models: [
      m("Fabia", "فابيا", "CITY_CAR"),
      m("Scala", "سكالا", "FAMILY"),
      m("Octavia", "أوكتافيا", "FAMILY"),
      m("Superb", "سوبيرب", "SEDAN"),
      m("Kamiq", "كاميك", "SUV"),
      m("Karoq", "كاروك", "SUV"),
      m("Kodiaq", "كودياك", "SUV"),
    ],
  },
  {
    brandFr: "Seat",
    brandAr: "سيات",
    tier: 1,
    models: [
      m("Ibiza", "إيبيزا", "CITY_CAR"),
      m("Leon", "ليون", "FAMILY"),
      m("Arona", "أرونا", "SUV"),
      m("Ateca", "أتيكا", "SUV"),
      m("Tarraco", "تاراكو", "SUV"),
    ],
  },
  {
    brandFr: "Cupra",
    brandAr: "كوبرا",
    tier: 2,
    models: [
      m("Formentor", "فورمنتور", "SUV"),
      m("Leon", "ليون", "FAMILY"),
      m("Ateca", "أتيكا", "SUV"),
      m("Born", "بورن", "FAMILY"),
    ],
  },
  {
    brandFr: "Tata",
    brandAr: "تاتا",
    tier: 0,
    models: [m("Indica", "إنديكا", "CITY_CAR"), m("Safari", "سفاري", "SUV"), m("Xenon", "زينون", "PICKUP")],
  },
  {
    brandFr: "ARO",
    brandAr: "أرو",
    tier: 0,
    models: [m("244", "244", "SUV"), m("10", "10", "PICKUP")],
  },
  {
    brandFr: "Lada",
    brandAr: "لادا",
    tier: 0,
    models: [m("Niva", "نيفا", "SUV"), m("Granta", "غرانتا", "SEDAN"), m("Vesta", "فيستا", "SEDAN")],
  },
  {
    brandFr: "Tesla",
    brandAr: "تسلا",
    tier: 3,
    models: [
      m("Model 3", "موديل 3", "SEDAN"),
      m("Model S", "موديل S", "SEDAN"),
      m("Model X", "موديل X", "SUV"),
      m("Model Y", "موديل Y", "SUV"),
      m("Cybertruck", "سايبرتراك", "PICKUP"),
    ],
  },
  {
    brandFr: "Ferrari",
    brandAr: "فيراري",
    tier: 4,
    models: [m("Roma", "روما", "FAMILY"), m("F8", "F8", "FAMILY"), m("SF90", "SF90", "FAMILY"), m("Purosangue", "بوروسانغوي", "SUV")],
  },
  {
    brandFr: "Lamborghini",
    brandAr: "لامبورغيني",
    tier: 4,
    models: [m("Huracan", "هوراكان", "FAMILY"), m("Revuelto", "ريفويلتو", "FAMILY"), m("Urus", "أوروس", "SUV")],
  },
  {
    brandFr: "Bentley",
    brandAr: "بنتلي",
    tier: 4,
    models: [m("Bentayga", "بنتايغا", "SUV"), m("Continental GT", "كونتيننتال جي تي", "FAMILY"), m("Flying Spur", "فلاينغ سبور", "SEDAN")],
  },
  {
    brandFr: "Rolls-Royce",
    brandAr: "رولز رويس",
    tier: 4,
    models: [m("Ghost", "غوست", "SEDAN"), m("Phantom", "فانتوم", "SEDAN"), m("Cullinan", "كولينان", "SUV")],
  },
  {
    brandFr: "Porsche",
    brandAr: "بورش",
    tier: 4,
    models: [
      m("718 Cayman", "718 كايمان", "FAMILY"),
      m("911", "911", "FAMILY"),
      m("Panamera", "باناميرا", "SEDAN"),
      m("Macan", "ماكان", "SUV"),
      m("Cayenne", "كايين", "SUV"),
      m("Taycan", "تايكان", "SEDAN"),
    ],
  },
  {
    brandFr: "Mini",
    brandAr: "ميني",
    tier: 2,
    models: [
      m("Cooper", "كوبر", "CITY_CAR"),
      m("Countryman", "كونتريمان", "SUV"),
      m("Clubman", "كلوبمان", "FAMILY"),
    ],
  },
];
